### ISSUE TITLE
problems running main.py

### ISSUE THREAD

**Issue by VahidGh** [openworm/muscle_model#17]
Trying to run this command:

>>> python run.py eval_file0 40.041444758152295 0.0 4514.250191560498 35.2 0.4089 0.6 --compile --plotoverlay

generates some errors in main.py. Most of errors are due to naming parameters, such as:

- line 87: __init__() got an unexpected keyword argument 'ion_channels'
	- replacing ion_channels with ion_channel solved the problem

- line 112: self.cell.leak_current = self.leak
	- we do not have cell attribute

- NameError: global name 'kinetics' is not defined
	- adding "from neuron import h" and replacing kinetics with h solved the problem

- AttributeError: muscle_simulation instance has no attribute 'morphology'
	- I guess there is some problem in neuroml.Segment usage

And so on...

**Comment by slarson** [comment]
@VahidGh is this still an issue?

**Comment by VahidGh** [comment]
Followed your [instructions](https://github.com/openworm/muscle_model/issues/1#issuecomment-70426727), and checked out libNeuroML from development. 
Got an error during [compilation](https://github.com/openworm/muscle_model/issues/1#issuecomment-70426727), commenting out [this line](https://github.com/openworm/muscle_model/blob/master/pyramidal_implementation/PyramidalSimulation.cpp#L32) solved the compilation issue. 
But still the same problems when running this command:
`python run.py eval_file0 40.041444758152295 0.0 4514.250191560498 35.2 0.4089 0.6 --compile --plotoverlay`

NameError: global name 'kinetics' is not defined

**Comment by travs** [comment]
Yeah I am still getting the same errors with most recent libNeuroML as well, but I am assuming this is because the code hasn't been [updated](https://github.com/openworm/muscle_model/issues/18#issuecomment-65801628) yet, or has it?

**Comment by pgleeson** [comment]
@VahidGh @travs, unfortunately the main.py won't work unless the updates outlines in #18 are implemented. I hope to get round to this next week.

**Comment by pgleeson** [comment]
Think this can be closed as much of the code for neurotune etc. has moved on past its old usage in main.py etc. and pyramidal is no longer supported...

**Comment by travs** [comment]
Ok, great. If this problem somehow arises again we can reopen.
