### ISSUE TITLE
Update optimization.py to run with neurotune instead of optimalneuron

### ISSUE THREAD

**Issue by VahidGh** [openworm/muscle_model#18]
Based on the changes in the *neurotune*, I guess *optimalneuron* should be replaced with *neurotune* in the *optimization.py*.

**Comment by VahidGh** [comment]
@pgleeson, Could you please explain what is the meaning of [these gating parameters](https://github.com/openworm/muscle_model/blob/master/pyramidal_implementation/main.py#L156), and why do we choose these values?

**Comment by pgleeson** [comment]
I wouldn't take any meaning from those particular values, they look like they are based on the HH model and probably were used just for testing. It's a long time since that code worked...

**Comment by VahidGh** [comment]
@pgleeson, Thanks for your reply. I was going to look if I can do something with this code, regarding to the optimization case study issue. 
Is this still your suggested pipeline? or it could be implemented easier via Pynml, now?

**Comment by VahidGh** [comment]
@pgleeson, another question related to the gating states of an ion channel: is there a way that I can represent a Markov model (gating dynamics) via NeuroML2/LEMS?

**Comment by pgleeson** [comment]
For your 2nd question, see here an example of a kinetic scheme based channel specification in NeuroML2: https://github.com/NeuroML/NeuroML2/blob/development/LEMSexamples/LEMS_NML2_Ex4_KS.xml. This runs with jNeuroML (but not jNeuroML->NEURON), but I don't believe this channel type has been tested/used beyond this example...

Re optimisation, I started [this](https://github.com/openworm/CElegansNeuroML/blob/master/CElegans/pythonScripts/c302/tune/c302tuner.py) updated version of the optimiser code to work with c302, but it's not yet finished. Have a look if you like. Requires my forks of neurotune and pyelectro. Hope to get this more stable in the next week.

**Comment by VahidGh** [comment]
Actually I needed that type of gating kinetics for other purposes (representing channel kinetics with Markov models I saw in some studies). Although here was not a right place to ask the question, but thank you for your explanation :)

**Comment by pgleeson** [comment]
This issue is redundant, due to the work ongoing to use neurotune in c302, see https://github.com/openworm/CElegansNeuroML/blob/master/CElegans/pythonScripts/c302/tune/c302tuner.py, and ChannelWorm https://github.com/VahidGh/ChannelWorm/tree/cwFitter/cwFitter.

The code in this repo using neurotune/optimalneuron probably won't be revived (sorry @vellamike)...

**Comment by VahidGh** [comment]
@pgleeson, Now I'm much more familiar with all these stuff. I can also work on this if we need to.
