### ISSUE TITLE
generate I-V plots for ion channels

### ISSUE THREAD

**Issue by VahidGh** [openworm/muscle_model#20]
Following discussions in [this](https://github.com/openworm/OpenWorm/issues/169) issue, in order to compare I-V plots for each ion channel with the corresponding plot from literature, we need some script.
Here we have [this one](https://github.com/rayner/BlueBrainProjectShowcase/blob/master/Channelpedia/iv_analyse.py) which is not compatible with the last updates (in the new version, something like `jnml LEMS_Test_k_fast.xml` generates m_inf, m_tau ,etc *.dat* files, which also lacks h_inf , h_tau *.dat* files, in the case of Ca ion channel).
Temporally, I wrote [this script](https://github.com/VahidGh/muscle_model/blob/master/BoyleCohen2008/PythonSupport/Main_Version/iv_all.py) which in, the out-most generated curve is the needed one, but finally we need some code to generate the plots from LEMS file.

**Comment by rayner** [comment]
I just updated the iv_analyse.py script so that it looks at all i_*.lems.dat files in the current directory, instead of relying on a hard-coded list.

I've also added a "peak absolute value" output column and graph, to help with replicating the Ca channel I/V graph.

The plots produced by this seem to be inverted relative to the ones in Boyle & Cohen (2008), so I think our simulation must be recording the current on the opposite side of the membrane to theirs, or something along those lines.

**Comment by VahidGh** [comment]
Thank you @rayner , but in the new version of the [LEMS template](https://github.com/OpenSourceBrain/BlueBrainProjectShowcase/blob/master/Channelpedia/LEMS_Test_template.xml), we have m_tau, m_inf, etc .dat output files instead of i_*.lems.dat (if we are going to use the new template)
Also, I was working on your python version of the main matlab version then, and I could generate curves close to what we needed with parameters from the main input.csv file (if we use the same parameters here, we should have the same result!):
![i-v_curves_ca_k](https://cloud.githubusercontent.com/assets/6655104/5602071/d7e18508-9349-11e4-89c8-2e9455c111ae.png)

In general, for validation purposes, it would be great if we've had some general script to compare every ion channel model we use in the project, with the curves and parameters from literature.

**Comment by slarson** [comment]
@VahidGh following today's meeting; let me know if you are able to use the modified template under [Rayner's fork of the BlueBrainShowcase](https://github.com/rayner/BlueBrainProjectShowcase/tree/master/Channelpedia) to generate the I/V plots as he showed today.  We'll be moving this into the OpenWorm organization soon.

**Comment by VahidGh** [comment]
@slarson Yes, that's working.

**Comment by slarson** [comment]
@VahidGh great!  Can we close this issue then?

**Comment by VahidGh** [comment]
It depends on what do we expect from the output of these curves.
If the aim is to compare every ion channel's I-V relationship from literature with our simulations, then we have to improve this one. 
But if we are going to be sure of the validity of our simulation of these 3 ion channels from Boyle & Cohen model, then with a negligible, we can close this issue (for example, by dividing the currents value of the inverted version of the Ca ion channel by the membrane conductance value (manually, because Cmem is not accessible from this script), it is comparable with the I-V curve from [this](http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2173050/) paper.

**Comment by VahidGh** [comment]
@slarson, With the help of @pgleeson's [CompareToNeuroML2 script](https://github.com/openworm/muscle_model/blob/master/BoyleCohen2008/PythonSupport/Main_Version/compareToNeuroML2.py), added [this script](https://github.com/openworm/muscle_model/blob/master/BoyleCohen2008/PythonSupport/Main_Version/iv_from_nml.py) that generates the I-V plots of interest from our NeuroML2 files:
![i-v_curves_ca_k_from_nml](https://cloud.githubusercontent.com/assets/6655104/5887112/a566ba44-a3d4-11e4-8692-f0fb10997e66.png)

One problem is with the inactivation expressions, that surprisingly missing from the [original Matlab version](https://github.com/openworm/muscle_model/blob/master/BoyleCohen2008/MatlabSupport/Main_Version/iv.m). it seems that the combination of values -5 for k_f and 25.2 for V_half_f, causing neglition of the inactivation expression for the whole Ca current. I'm working on this issue...

Another TO DO is to generalize this script for #30 that the script could get any channel NeuroML2 file (and some other parameters as input) and generate an I-V plot.

**Comment by rgerkin** [comment]
I left a comment in #30 about a small problem I am having in these simulations.  It may be a function of my implementation.

**Comment by slarson** [comment]
@VahidGh Awesome progress!  Question -- can we post the target values for these curves that come from digitising the figures directly from the papers?  I'm envisioning a script that enables us to plot both the real and simulated data on top of each other and then quantifies how close the fit is in a manner that can be fed into a unit test.

**Comment by VahidGh** [comment]
Yes, As an example, I digitized the figure from #30, I can do the same here.
FYI, [Plotly](https://plot.ly/api/) also provides some great API which are very useful. 
I think we can do something about this plotting comparison issue via it's [Github Python API](https://github.com/plotly/python-api).

**Comment by VahidGh** [comment]
[This](https://plot.ly/56/~VahidGh) is the digitized version of this plot:
![ca_i-v_digitized](https://cloud.githubusercontent.com/assets/6655104/6027361/b509831c-abf6-11e4-95a4-372b911533fb.png)

**Comment by slarson** [comment]
There are now several ways to this; recommend way [is here](https://github.com/NeuroML/pyNeuroML/issues/5#issuecomment-110011283)
