### ISSUE TITLE
Add jneuroML to documentation here

### ISSUE THREAD

**Issue by travs** [openworm/muscle_model#45]
@cheelee [said](https://github.com/VahidGh/ChannelWorm/issues/93):

In the muscle_model repository, NeuroML2 folder. The README.md instructions ask the user to try:
jnml LEMS_Figure2A.xml

but does not explain how one should get hold of jnml. For me, I found it in the jNeuroML repository, cloned it, and followed the README.md instructions there. That appeared to be successful, and I was subsequently able to run from the jNeuroML folder:

./jnml /muscle_model/NeuroML2/LEMS_Figure2A.xml

**Comment by travs** [comment]
Also related to #29

**Comment by pgleeson** [comment]
My motivation with this was to have one place with (clear?) instructions on installing jNeuroML (the main repo Readme), as they may change (e.g. the binaries are installed from Sourceforge which is not ideal).

**Comment by travs** [comment]
Ok, that makes sense. I was actually looking at the top-level readme by mistake. The instructions to install jNeuroML are pointed to in the readme mentioned, so this can be closed.
