### ISSUE TITLE
Replace jnml in scripts with pynml?

### ISSUE THREAD

**Issue by travs** [openworm/muscle_model#47]
@gsarma and I have been running some things in this repo recently, but we couldn't get jNeuroML to install correctly. If we replaced calls to `jnml` with `pynml` they seemed to work fine and produce output.

There are only [a few](https://github.com/openworm/muscle_model/search?utf8=%E2%9C%93&q=jnml) places where we would have to replace this.

@pgleeson Do you think the functionality in pyNeuroML is such that we can do this right now?

**Comment by cheelee** [comment]
I was previously able to build jnml using the jNeuroML repository instructions. It was a little clunky to use but it worked. Having said that, if it works with just pynml I'd suggest sticking to just one set of instructions initially for users.

**Comment by pgleeson** [comment]
I've made some more updates here: https://github.com/openworm/muscle_model/blob/master/NeuroML2/README.md.

If there are specific issues with the installation instructions of jnml, please add details https://github.com/NeuroML/jNeuroML/issues.

PyNeuroML is probably stable enough that the installation details from .travis.yml could be replaced in section 2.1 of the main README.
