### ISSUE TITLE
The same conductance for different channels in nml files

### ISSUE THREAD

**Issue by VahidGh** [openworm/muscle_model#49]
@pgleeson, [Channel nml files](https://github.com/openworm/muscle_model/tree/master/NeuroML2) for Boyle&Cohen 2008 model, all have the same conductance value (10ps) and different from conductance values described in [this notebook file](http://nbviewer.ipython.org/github/openworm/muscle_model/blob/master/NeuroML2/Explore.ipynb) and generated by [this script](https://github.com/openworm/muscle_model/blob/master/BoyleCohen2008/PythonSupport/Main_Version/compareToNeuroML2.py).
I also found the same value for [other examples](https://github.com/NeuroML/NeuroML2/blob/master/examples/NML2_SimpleIonChannel.nml) of NeuroML2 channel files.
If it is OK, then how different conductance values could be used in neuroML2 files? and which one is preferred?

**Comment by pgleeson** [comment]
There's an important distinction between the conductance of an individual channel (set in ionChannel .. conductance="10pS") and the conductance density of a distributed conductance on a cell (set in biophysicalProperties/membraneProperties/channelDensity condDensity). 

The former is only really relevant when you think of the "ion channel" as a single individual channel which opens and allows a current with a time varying conductance. The latter is what's actually used in the cell models, and is different for each of the ion channels used in channelDensity elements.

**Comment by VahidGh** [comment]
So what if we would need to keep it inside the channel file, independent of the cell file?
Do you recommend this? or we should have both the cell file and the channel file for each model?

**Comment by pgleeson** [comment]
In short, yes, they're 2 different things. One is a property of the channel itself (which is not really used much and could be set to zero) and the other is only relevant for when you place it on an actual cell and need to say the density at which that particular conductance is present on the cell. So a value for conductance density shouldn't be put in the channel file.

**Comment by VahidGh** [comment]
@pgleeson, OK, thanks. Is there any neat python code I can use for generating channel, cell, and LEMS file for an ion channel?

**Comment by pgleeson** [comment]
See examples mentioned in https://github.com/openworm/muscle_model/issues/31#issuecomment-128332835. Also https://github.com/NeuralEnsemble/libNeuroML/tree/development/neuroml/examples

**Comment by VahidGh** [comment]
Was so useful, thanks.
