### ISSUE TITLE
Muscle Model Explorer - Error while loading channel files

### ISSUE THREAD

**Issue by shah-n** [openworm/muscle_model#61]
For the muscle model explorer, I am receiving an error when loading channel files. The ca_boyle channel has an h gate without the time_course and steady_state attributes.  

I copied the source code from the muscle model explorer IPython notebook (http://bit.ly/2c6GO2c) to a .py file. Afterwards, I ran the python file at the command prompt. 

Attached is the source code and output.

[muscle_model_explorer.txt](https://github.com/openworm/muscle_model/files/450993/muscle_model_explorer.txt)

[muscle_model_explorer_output.txt](https://github.com/openworm/muscle_model/files/450996/muscle_model_explorer_output.txt)

**Comment by pgleeson** [comment]
Good point. The h gate in the  ca channel is different, it uses [a custom type](https://github.com/openworm/muscle_model/blob/master/NeuroML2/ca_boyle.channel.nml) which doesn't have a standard Hodgkin Huxley description involving timeCourse/steadyState, but instead is a function of [Ca2+].

I've updated the  IPython notebook to reflect this.

**Comment by shah-n** [comment]
Error is now gone.  Thank you for your help with this.
